
set(FLINTJVM_SRCS
    "../../../ESPJVM/FlintJVM/VM/Src/flint.cpp"
    "../../../ESPJVM/FlintJVM/VM/Src/flint_utf8.cpp"
    "../../../ESPJVM/FlintJVM/VM/Src/flint_hook.cpp"
    "../../../ESPJVM/FlintJVM/VM/Src/flint_mutex.cpp"
    "../../../ESPJVM/FlintJVM/VM/Src/flint_common.cpp"
    "../../../ESPJVM/FlintJVM/VM/Src/flint_const_pool.cpp"
    "../../../ESPJVM/FlintJVM/VM/Src/flint_fields_data.cpp"
    "../../../ESPJVM/FlintJVM/VM/Src/flint_field_info.cpp"
    "../../../ESPJVM/FlintJVM/VM/Src/flint_method_info.cpp"
    "../../../ESPJVM/FlintJVM/VM/Src/flint_java_class.cpp"
    "../../../ESPJVM/FlintJVM/VM/Src/flint_java_object.cpp"
    "../../../ESPJVM/FlintJVM/VM/Src/flint_java_string.cpp"
    "../../../ESPJVM/FlintJVM/VM/Src/flint_java_thread.cpp"
    "../../../ESPJVM/FlintJVM/VM/Src/flint_java_throwable.cpp"
    "../../../ESPJVM/FlintJVM/VM/Src/flint_array_object.cpp"
    "../../../ESPJVM/FlintJVM/VM/Src/flint_class_loader.cpp"
    "../../../ESPJVM/FlintJVM/VM/Src/flint_execution.cpp"
    "../../../ESPJVM/FlintJVM/VM/Src/flint_debugger.cpp"
    "../../../ESPJVM/FlintJVM/VM/Src/flint_utf8_dict_node.cpp"
    "../../../ESPJVM/FlintJVM/VM/Src/flint_file_reader.cpp"
    "../../../ESPJVM/FlintJVM/VM/Src/flint_zip_file_reader.cpp"
    "../../../ESPJVM/FlintJVM/VM/Src/flint_java_class_dict_node.cpp"
    "../../../ESPJVM/FlintJVM/VM/Src/flint_java_string_dict_node.cpp"
    "../../../ESPJVM/FlintJVM/VM/Src/flint_native_interface.cpp"
    "../../../ESPJVM/FlintJVM/Impl/Src/fatfs_system_io_api.cpp"
    "../../../ESPJVM/FlintJVM/Impl/Src/lwip_system_net_api.cpp"
    "../../../ESPJVM/FlintJVM/Impl/Src/freertos_system_thread_api.cpp"

    "../../../ESPJVM/FlintJVM/Native/Common/Src/flint_native.cpp"
    "../../../ESPJVM/FlintJVM/Native/Common/Src/flint_native_common.cpp"

    "../../../ESPJVM/FlintJVM/Native/Base/Src/flint_native_math.cpp"
    "../../../ESPJVM/FlintJVM/Native/Base/Src/flint_native_class.cpp"
    "../../../ESPJVM/FlintJVM/Native/Base/Src/flint_native_array.cpp"
    "../../../ESPJVM/FlintJVM/Native/Base/Src/flint_native_float.cpp"
    "../../../ESPJVM/FlintJVM/Native/Base/Src/flint_native_double.cpp"
    "../../../ESPJVM/FlintJVM/Native/Base/Src/flint_native_object.cpp"
    "../../../ESPJVM/FlintJVM/Native/Base/Src/flint_native_string.cpp"
    "../../../ESPJVM/FlintJVM/Native/Base/Src/flint_native_system.cpp"
    "../../../ESPJVM/FlintJVM/Native/Base/Src/flint_native_thread.cpp"
    "../../../ESPJVM/FlintJVM/Native/Base/Src/flint_native_method.cpp"
    "../../../ESPJVM/FlintJVM/Native/Base/Src/flint_native_character.cpp"
    "../../../ESPJVM/FlintJVM/Native/Base/Src/flint_native_reflection.cpp"
    "../../../ESPJVM/FlintJVM/Native/Base/Src/flint_native_constructor.cpp"
    "../../../ESPJVM/FlintJVM/Native/Base/Src/flint_native_file.cpp"
    "../../../ESPJVM/FlintJVM/Native/Base/Src/flint_native_file_descriptor.cpp"
    "../../../ESPJVM/FlintJVM/Native/Base/Src/flint_native_file_input_stream.cpp"
    "../../../ESPJVM/FlintJVM/Native/Base/Src/flint_native_file_output_stream.cpp"

    "../../../ESPJVM/FlintJVM/Native/Net/Src/flint_native_flint_socket_impl.cpp"
    "../../../ESPJVM/FlintJVM/Native/Net/Src/flint_native_flint_inet_address_impl.cpp"
    "../../../ESPJVM/FlintJVM/Native/Net/Src/flint_native_flint_socket_input_stream.cpp"
    "../../../ESPJVM/FlintJVM/Native/Net/Src/flint_native_flint_socket_output_stream.cpp"
    "../../../ESPJVM/FlintJVM/Native/Net/Src/flint_native_flint_datagram_socket_impl.cpp"
)

set(FLINTJVM_INCS
    INCLUDE_DIRS "../../../ESPJVM/FlintJVM/VM/Inc"
    INCLUDE_DIRS "../../../ESPJVM/FlintJVM/Impl/Inc"
    INCLUDE_DIRS "../../../ESPJVM/FlintJVM/Native/Net/Inc"
    INCLUDE_DIRS "../../../ESPJVM/FlintJVM/Native/Base/Inc"
    INCLUDE_DIRS "../../../ESPJVM/FlintJVM/Native/Common/Inc"
)
